# action.yml
name: 'NLU Hyperopt'
description: 'Find optimal hyperparameters for NLU model'
outputs:
  best-intent-f1: # id of output
    description: 'best intent macro averaged f1 score found'
runs:
  using: 'docker'
  image: 'Dockerfile'
  
  
