version: "3"

services:
  # Database which will store the evaluation results and is used to coordinate
  # the hyperparameter search.
  mongodb:
    image: "mongo"
    ports:
    - "27017:27017"
    container_name: "mongodb"
    volumes:
    - ./volumes/mongo:/data/db
  
  # Master service which leads the hyperparameter search.
  hyperopt-master:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    environment:
      EXP_KEY: ${EXPERIMENT_KEY}
      MAX_EVALS: ${MAX_EVALS}
      MONGO_URL: ${MONGO_URL}
  
  # Workers which train and evaluate the NLU model.
  hyperopt-worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - hyperopt-master
      - mongodb
    environment:
      MONGO_URL: ${MONGO_URL}
      DATA_DIRECTORY: ${DATA_DIRECTORY}
      MODEL_DIRECTORY: ${MODEL_DIRECTORY}
      TARGET_METRIC: ${TARGET_METRIC}
      THRESHOLD: ${THRESHOLD}
      ABOVE_BELOW_WEIGHT: ${ABOVE_BELOW_WEIGHT}
    command:
      - "/scripts/nlu-hyperopt-worker"
      - "--mongo=${MONGO_URL}"
      - "--poll-interval=0.1"
    volumes:
     - ./volumes/models:/models/
