version: "3"

services:
  # Database which will store the evaluation results and is used to coordinate
  # the hyperparameter search.
  mongodb:
    image: "mongo"
    ports:
    - "27017:27017"
    container_name: "mongodb"
    volumes:
    - ./volumes/mongo:/data/db
  
  # Master service which leads the hyperparameter search.
  hyperopt-master:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    environment:
      INPUT_EXP_KEY: ${INPUT_EXPERIMENT_KEY}
      INPUT_MAX_EVALS: ${INPUT_MAX_EVALS}
      INPUT_MONGO_URL: ${INPUT_MONGO_URL}
  
  # Workers which train and evaluate the NLU model.
  hyperopt-worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - hyperopt-master
      - mongodb
    environment:
      INPUT_MONGO_URL: ${INPUT_MONGO_URL}
      INPUT_DATA_DIRECTORY: ${INPUT_DATA_DIRECTORY}
      INPUT_MODEL_DIRECTORY: ${INPUT_MODEL_DIRECTORY}
      INPUT_TARGET_METRIC: ${INPUT_TARGET_METRIC}
      INPUT_THRESHOLD: ${INPUT_THRESHOLD}
      INPUT_ABOVE_BELOW_WEIGHT: ${INPUT_ABOVE_BELOW_WEIGHT}
    command:
      - "/scripts/nlu-hyperopt-worker"
      - "--mongo=${INPUT_MONGO_URL}"
      - "--poll-interval=0.1"
    volumes:
     - ./volumes/models:/models/
