
name: main
on: [pull_request]

jobs:
  nlu-hyperopt:
    name: NLU hyperparameter optimization
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: RasaHQ/nlu-hyperopt@rasa-1-compat
      name: Run NLU Hyperoptimization
      with:
        max_evals: 10 
        target_metric: f1_score
        data_directory: ${{ github.workspace }}/data
        search_space: ${{ github.workspace }}/nlu_hyperopt/space.py
      