
name: nlu-hyperopt
on: [pull_request]

jobs:
  nlu-hyperopt:
    name: NLU hyperoptimization
    runs-on: ubuntu-latest
    steps:
      - name: NLU hyperoptimization
        id: nluhyperopt
        uses: RasaHQ/nlu-hyperopt@rasa-1-compat